{
 "title": "Aura Testnet",
 "description": "Prometheus for system metrics. \r\nLoad, CPU, RAM, network, process ... ",
 "tags": [
  "cosmos",
  "blockchain",
  "validator"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "host", "label": "Host", "query": { "query": "label_values($tag)" } },
   { "name": "tag", "query": "instance, alias" }
  ]
 },
 "panels": [
  {
   "title": "Latest Block",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_latest_block_height{chain_id=\"euphoria-1\"}"
    }
   ]
  },
  {
   "title": "Missed Blocks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validator_missed_blocks{chain_id=\"euphoria-1\"}"
    }
   ]
  },
  {
   "title": "N of Peers",
   "type": "stat",
   "description": "Number of peers node's connected to\n\n(Need to change Threshold)",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{chain_id=\"euphoria-1\"}"
    }
   ]
  },
  {
   "title": "Power Alert",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_validator_power{chain_id=\"euphoria-1\",validator_address=\"C4147229D2A4C4A323FB605F88209688EEA76546\"}"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "tendermint_consensus_validator_last_signed_height{chain_id=\"euphoria-1\",validator_address=\"C4147229D2A4C4A323FB605F88209688EEA76546\"}"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": " sum(tendermint_consensus_validator_last_signed_height{chain_id=\"euphoria-1\",validator_address=\"C4147229D2A4C4A323FB605F88209688EEA76546\"}) - sum(tendermint_consensus_validator_last_signed_height{chain_id=\"euphoria-1\",validator_address=\"C4147229D2A4C4A323FB605F88209688EEA76546\"} offset 1m)"
    }
   ]
  },
  {
   "title": "Last Signed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validator_last_signed_height{chain_id=\"euphoria-1\",validator_address=\"C4147229D2A4C4A323FB605F88209688EEA76546\"}"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators{chain_id=\"euphoria-1\"}"
    }
   ]
  },
  {
   "title": "Delegation",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validator_power{chain_id=\"euphoria-1\",validator_address=\"C4147229D2A4C4A323FB605F88209688EEA76546\"}"
    }
   ]
  },
  {
   "title": "Block Processing Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(tendermint_state_block_processing_time_bucket{chain_id=\"euphoria-1\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Mempool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_mempool_size{chain_id=\"euphoria-1\"}"
    }
   ]
  }
 ]
}